### ISSUE TITLE
Got `TypeError: (0 , _walletconnect_utils__WEBPACK_IMPORTED_MODULE_12__.isOnline) is not a function` error after upgrading to 1.4.2 from 1.3.9

### ISSUE THREAD

**Issue by jingxuan98** [wagmi-dev/wagmi#3024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.2

Other package ver:
"@rainbow-me/rainbowkit": "^1.0.11"
"viem": "1.10.7"

### Current Behavior

Got `TypeError: (0 , _walletconnect_utils__WEBPACK_IMPORTED_MODULE_12__.isOnline) is not a function` error after upgrading wagmi from 1.3.9 to 1.4.2

![Screenshot 2023-09-19 at 3 18 05 PM](https://github.com/wagmi-dev/wagmi/assets/43902263/18caba31-bcce-4eb8-90da-2327cf412e43)

### Expected Behavior

should be no error

### Steps To Reproduce

1. upgrade from wagmi from 1.3.9 to 1.4.2

**Comment by jingxuan98** [comment]
Solved by deleting my node_moduels folder
