### ISSUE TITLE
bug: EthereumProvider.init is not a function

### ISSUE THREAD

**Issue by parmesh-shiroya** [wagmi-dev/wagmi#2638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.18

### Current Behavior

React test throwing below error. when updating walletConnect to v2
```
TypeError: EthereumProvider.init is not a function
 ❯ WalletConnectConnector.initProvider_fn node_modules/@wagmi/connectors/dist/walletConnect.js:222:58 
```

testing lib : vitest
I used rainbowkit for connect : "@rainbow-me/rainbowkit": "0.12.15",

**Comment by oxSaturn** [comment]
Ran into the same issue when using vitest to test React components. There was a similar report on @wagmi/connectors https://github.com/wagmi-dev/references/issues/370.
